/* This file was generated by Payload. */
import { NotFoundPage, generatePageMetadata } from '@payloadcms/next/views'

import config from '@payload-config'

type Args = {
  params: Promise<{
    segments: string[]
  }>
  searchParams: Promise<{
    [key: string]: string | string[]
  }>
}

export const generateMetadata = ({ params, searchParams }: Args) =>
  generatePageMetadata({ config, params, searchParams })

const NotFound = ({ params, searchParams }: Args) =>
  NotFoundPage({
    config,
    params,
    searchParams,
    importMap: {
      '@payload-config': config,
    },
  })

export default NotFound
